global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/alert-rules.yml

scrape_configs:
  - job_name: api-services
    metrics_path: /health/deep
    static_configs:
      - targets:
          - api-ios:8080
          - api-android:8080
          - api-web:8080
          - api-admin:8080
          - worker:8080

  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
