storage:
  dbPath: /data/db

systemLog:
  destination: file
  path: /data/db/mongod.log
  logAppend: true

net:
  bindIp: 0.0.0.0
  port: 27017

replication:
  replSetName: menorah-rs
  oplogSizeMB: 20480

security:
  authorization: enabled
  keyFile: /data/db/mongo-keyfile

processManagement:
  timeZoneInfo: /usr/share/zoneinfo
